site_name: Roblox Dev Organization Guide
site_description: Documentation for GreenUtils
site_url: https://greentheblaze.github.io/Roblox-Dev-Organization-Guide/

repo_name: GreenTheBlaze/Roblox-Dev-Organization-Guide
repo_url: https://github.com/GreenTheBlaze/Roblox-Dev-Organization-Guide
edit_uri: ""

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: preference
      primary: 'Light Blue'
      accent: 'Light Blue'
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: preference
      primary: 'Light Blue'
      accent: 'Light Blue'
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  highlightjs: true
  hljs_languages:
    - lua
    - luau

extra_javascript:
  - javascripts/tags.js

markdown_extensions:
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences

nav:
  - Home: index.md
  - Introduction: introduction.md
  - File Organization: file-organization.md
  - Scripting Style Guide: scripting-style-guide.md
