site_name: Roblox Dev Organization Guide
site_description: Documentation for GreenUtils
site_url: https://greentheblaze.github.io/Roblox-Dev-Organization-Guide/

repo_name: GreenTheBlaze/Roblox-Dev-Organization-Guide
repo_url: https://github.com/GreenTheBlaze/Roblox-Dev-Organization-Guide
edit_uri: ""

theme:
  name: material
  features:
    - navigation.footer
  palette:
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/link
    #     name: Switch to light mode
    # - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      # toggle:
      #   icon: material/toggle-switch
      #   name: Switch to dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   primary: green
    #   accent: green
    #   toggle:
    #     icon: material/toggle-switch-off
    #     name: Switch to system preference
  
  # highlightjs: true
  # hljs_languages:
  #   - lua

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - tables
  - admonition
  # - codehilite:
  #     guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
     # use_pygments: true
  #   linenums: false
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.extra
  - attr_list

nav:
  - Home: index.md
  - File Organization: file-organization.md
  - Scripting Style Guide: scripting-style-guide.md
  - Test: test-code.md
